scripts/d18thday-HNG-00677.js
D18thday pulling from TomiwaAjayi
=> d18thday-HNG-00677.js

scripts/orim.dominic-HNG-02549.js
Add orimdominic script to the repo for the task
=> add orimdominic script

scripts/fakorede.damilola-HNG-02102.js
=> fakorede.damilola-HNG-02102 script

scripts/TonyEneh-HNG-05305.js
=> TonyEneh-HNG-05305 script

scripts/HezekiahFeyisayo-HNG-00738.js
HezekiahFeyisayo-HNG-00738 script
=> HezekiahFeyisayo-HNG-00738 script

scripts/olajames-HNG-03683.py
olajames is requesting to add script
=> olajames-HNG-03683 script

scripts/Chiazam-HNG-02112.js
This is a JavaScript that prints out an Intern's  Information by ogbonnnaya chinonyerem chiazam.
=> Printing Intern's  HNG-02112 information With JavaScript

scripts/folek-HNG-05189.js
=> folek-HNG-05189 script

scripts/venny-HNG-01916.js
Team Fierce; Hope am good to go
=> venny-HNG-01916 script

scripts/sccola-HNG-00167.js
Team Task completed (HNGi7 Task 2).
=> sccola-HNG-00167 script

scripts/Emysilva-HNG-02071.js
I added my javascript file to display my name, id, and language used.
=> Emysilva-HNG-02071 script

scripts/Emysilva-HNG-02071.js
I added my email to the console
=> added my email

scripts/gfellah-HNG-02163.js
hello! Kindly review and merge
Regards
=> gfellah-HNG-02163 script

scripts/noCodeName-HNG-05098.js
1. Added my script file that will print a message containing my full name, script language and HNG id.
=> noCodeName-HNG-05098 script

scripts/suleimanAbdullateef-HNG-04493.js
Suleiman Abdullateef, HNG-04493 Task 2 first commit
=> Suleiman Abdullateef, HNG-04493 Task 2 first commit

index.php, scripts/Kubiat-HNG-00446.js
**What is in this PR?**
- Added the base code structure for the index.php
- Added a test script in the `scripts` folder
**How to test?**
- Clone the repo
- Run `php index.php` on your bash or terminal
- Alternatively run the folder through a `local` server on your machine
=> Feat(*): add index file structure

scripts/denniman-HNG-00846.js
My script is ready, please approve.
=> Denniman-HNG-00846 script

scripts/okaforelvis-HNG-03728.js
=> okaforelvis-HNG-03728 script

scripts/jafar-HNG-06280.js
Please merge PR.
jafar-HNG-06280
=> jafar-HNG-06280 script

scripts/Ekom-HNG-00782.js
=> Ekom-HNG-00782 script

scripts/Louis1-HNG-01775.py
=> Louis1-HNG-01775.py

scripts/abraham-HNG-04455.js
abraham-HNG-04455 script for task 2
=> abraham-HNG-04455 script

scripts/Hybee-HNG-01074.js
Here's my script for task 2... 
Slack ID: @Hybee
HNG ID: HNG-01074
=> Hybee-HNG-01074 script

scripts/Magni-HNG-00568.php
Hello, could you please assess my work and leave a feedback thank you.
=> Magni-HNG-00568 script

scripts/Kuldek-HNG-01241.js
=> Kuldek-HNG-01241 script

scripts/dotmanl-HNG-05961.js
Kindly review and merge my HNG task 2 script.
From dotmanl
=> dotmanl-HNG-05961 script

scripts/femiyhogurt-HNG-00716.js
=> femiyhogurt-HNG-00716

scripts/sproff-HNG-02880.js
=> added the email output

scripts/Chisom-HNG-03890.php
=> Add existing file

bamideletosin00281-HNG-ID.py
please merge Bamidele Tosin file to master.
=> bamideletosin00281-HNG-ID.py

bamideletosin00281-HNG-ID.py
Reverts tomiwaajayi/HNGi7-task-2#108
=> Revert "bamideletosin00281-HNG-ID.py"

scripts/newhasher-HNG-01855.py
=> newhasher-HNG-01855 script

scripts/Badiru-HNG-03140.php
Tomiwa asked to creating a commit and pull request on task 2
=> Git commit –m “Badiru- HNG-03140 script”

scripts/tosin-HNG-00281.py
please merge my file to master
=> tosin-HNG-00281.py

vijayablaze-HNG-04715.py
Reverts tomiwaajayi/HNGi7-task-2#91
Reason: Script wasn't in the scripts folder
=> Revert "Create vijayablaze-HNG-04715.py"

scripts/samueladeniyi-HNG-03373.php
=> samueladeniyi-HNG-03373 script

scripts/Temitope-HNG-03341.py
git commit -m "Temitope-HNG-03341 script
=> Temitope-HNG-03341.py

scripts/Oge-HNG-00932.js
=> Oge-HNG-00932-script

scripts/bcj-HNG-03425.js
=> bcj-HNG-03425 script

scripts/Oge-HNG-00932.js
**Task**
Updated Oge-HNG-00932 script
=> updated Oge-HNG-00932-script

scripts/milz-HNG-01472.js
created my script. check and merge
=> milz-HNG-01472 's script

scripts/kelvinc-HNG-02959.js
Hello, this is Kelvin O Chibuikem's  hngi7 task two for team-fierce.
Please feedback is welcomed.
My slack username = @kelvinc
=> Task Completed

scripts/muyi-HNG-00766.js
=> muyi-HNG-00766 script

scripts/devJuri-HNG-02049.php
=> devJuri-HNG-02049 script

scripts/Jxrry-HNG-00294.py
Reverts tomiwaajayi/HNGi7-task-2#184
=> Revert "Jxrry-HNG-00294 script"

scripts/Jxrry-HNG-00294.py
Reverts tomiwaajayi/HNGi7-task-2#194
=> Revert "Revert "Jxrry-HNG-00294 script""

scripts/urielone-HNG-04057.js
This is my script file for task 2 ,  thumbs up team fierce!!!
=> urielone-HNG-04057 script on team fierce

scripts/phildubem-HNG-04214.php
Added my own script to the scripts folder
=> phildubem-HNG-04214 script

scripts/faidah-HNG-04259.py
HNGi7 Task 2
Please merge my file with master. Thanks
=> faidah-HNG-04259.py

scripts/oyindamola-HNG-00456.js
=> bakare-oyindamola-HNG-00456 script

scripts/Abiye-HNG-01562.js
=> Abiye-HNG-01562 script

scripts/Oneharry-HNG-02652.js
This is the script for the task 2.
=> Oneharry-HNG-02652 script

scripts/Anuoluwapo-HNG-01297.php
I Anuoluwapo added a script file
=> Anuoluwapo-HNG-01297 script

scripts/adessica-HNG-06241.js
Hi, I am not entirely sure I did the process right please tag @adessica on stack to notify me if I have to redo it... I'd appreciate the heads up
=> adessica-HNG-06241 script

scripts/bmeera-HNG-02779.js
Hi, Ameerat requesting to have her script pulled into the team's repo.
=> bmeera-HNG-02779 script

scripts/arinze-HNG-02728.py
=> arinze-HNG-02728 script

scripts/proSource-HNG-00875.js
=> proSource-HNG-00875

scripts/Rouche01-HNG-01772.py
=> Rouche01-HNG-01772 script

scripts/Tobijudah-HNG-00357.js
=> Tobijudah-HNG-00357 script

scripts/tobyleye-HNG-04885.js
=> tobyleye-HNG-04885 script

scripts/judith-HNG-01759.py
Pull request from judith-HNG-01759.
=> judith-HNG-O1759 script

scripts/evanseburu32-HNG-05222.py
I, Evans is requesting to merge
=> evanseburu32-HNG-05222 script

scripts/dellshams-HNG-02100.js
=> dellshams-HNG-02100 script

scripts/sahmie-HNG-01730.js
=> sahmie-HNG-01730 script

chiomaike-HNG-04972.py
Reverts tomiwaajayi/HNGi7-task-2#246
Script wasn't placed in the scripts folder
=> Revert "chiomaike-HNG-04972 script"

scripts/Cornelia-HNG-01935.js
=> cornelia HNG-01935 script

scripts/CodeHunta-HNG-01135.py
#SayNoToRape #BlackLivesMatter
=> CodeHunta-HNG-01135 script

scripts/OyinbrakemiMenebraye_HNG_01869.php
=> Oyinbrakemi Menebraye HNG-01869 task using php

scripts/AdeyemiTimilehin-HNG-02251.js
Please help me merge the changes
=> Modify the Id

scripts/Magni-HNG-00568.php
Hello please i just added my email to my script.
=> modified the first file

scripts/philip-HNG-00037.py
hng script for promotion to stage 2.
=> HNG-00037 script.

scripts/Wisdom-HNG-01968.js
=> Wisdom-HNG-01968 script

scripts/philip-HNG-00037.py
=> corrected typo error

scripts/ronnycrown-HNG-00477.js
ronnycrown making a new pull request.
=> ronnycrown-HNG-00477 script

scripts/yusufsd-HNG-03612.js
Kindly check my script, Kudos everytime. Cheers!
=> yusufsd-HNG-03612 script

scripts/Gozie-HNG-00340.php
=> HNGi7 Task 2 pull request

scripts/Osiegbu Precious Ebere - hng-06360.py
=> Create Osiegbu Precious Ebere - hng-06360.py

scripts/OlumideAdewumi-HNG-01548.js
commit changes by OIumide Adewumi-06-04-2020. 11:18am
=> Olumide Adewumi-Hng-01548

scripts/dodo-HNG-06500.js
=> first commit

scripts/chiama89-HNG-02470.js, scripts/fakorede.damilola-HNG-02102 copy.js
Hello! Kindly review and merge
Regards
=> chiama89-hNG-02470

scripts/Tura-HNG-02324.js
=> Task Completed by Adeyemi Misturah With INTERNSHIP ID: HNG-02324

manyo-HNG-00604.js
Reverts tomiwaajayi/HNGi7-task-2#321
=> Revert "Create manyo-HNG-00604 script"

scripts/oyindamola-HNG-00456.js
ThugDeveloper-HNG-00456 scripts
=> ThugDeveloper-HNG-00456 scripts

scripts/alora-HNG-03349.php
=> alora-HNG-03349 script

scripts/sahmie-HNG-01730.js
=> refactor code to use functions

scripts/HadeelSalah-HNG-03648.js
This is  a new branch which includes some edits
=> Hadeel-HNG-03648

scripts/omokhefe-HNG-03023.js
=> omokhefe-03023 script

scripts/Philpat-HNG-01205.js
=> Philpat-HNG-01205.js

scripts/urielone-HNG-04057.js
I have changed the filename,  I don't know if there is still other errors
=> Changed the filename and errors 

scripts/Ramko-HNG-03960.py
my first script had no email so i updated it please review and merge
=> ramko-HNG-03960

scripts/tobechukwu-HNG-00711.js
=> adding Tobechukwu's script

scripts/phildaurch-HNG-04625.js
=> Added phildaurch-HNG-04625.js to script

scripts/Dtblaze-HNG-02096.js
=> Dtblaze added script for task 2

scripts/tolulope-HNG-00377.js
- This PR creates a script file
- Script file returns a message
=> tolulope-HNG-00377 script

scripts/Inya-HNG-00668.js
Hello Team, This is Amadi Inya Ogbonnia. Kindly cross check my work. 
If there is any error, kindly reach me on slack with username Inya
=> Inya-HNG-00668 script

scripts/sproff-HNG-02880.js
=> modified the letters

scripts/phrukey-HNG-04367.js
Corrected mistakes in the output.
=> phrukey-HNG-04367 script corrected some mistakes

scripts/emmacodemy-HNG-05860.js
edited emmacodemy-HNG-05860 task script.
=> updated emmacodemy-HNG-05860 task script

scripts/Afej-HNG-01110.js
Removed fullstop and updated some capital letters.
=> Afej-HNG-01110 script

scripts/stonecode-HNG-00352.js
=> stonecode-HNG-00352

scripts/Christian-HNG-03751.py
This pull request is from Christian
=> Christian-HNG-03751 script

scripts/iamsuigeneris-HNG-03106.js
=> iamsuigeneris-HNG-03106 script

scripts/CodeHunta-HNG-01135.py
=> CodeHunta-HNG-01135 Updated Script

scripts/ifeadewumi-HNG-00422.py
PR for ifeadewumi with ID HNG-00422
=> ifeadewumi-HNG-00422 script

scripts/brightsomtochukwu-HNG-05447.js
=> Create brightsomtochukwu-HNG-05447 script

scripts/HAKEEM-HNG-01232.js
=> HAKEEM-HNG-01232

scripts/El'zino-HNG-00350.py, scripts/Generalisimo-HNG-02735.js, scripts/WallaAdlan-HNG-00987.py, scripts/abdulhameed-HNG-02134.js, scripts/elotech-HNG-04399.py, scripts/hafolahbi-HNG-04788.py
Reverts tomiwaajayi/HNGi7-task-2#453
=> Revert "Hng 00987 2"

scripts/oyinda-HNG-00510.js
=> oyinda-HNG-00510 script

scripts/Toby-HNG-00389.js
Just got back from work and missed the email part. Please merge before submission.
=> toby-HNG-00389 script

scripts/El'zino-HNG-00350.py, scripts/Generalisimo-HNG-02735.js, scripts/WallaAdlan-HNG-00987.py, scripts/abdulhameed-HNG-02134.js, scripts/elotech-HNG-04399.py, scripts/hafolahbi-HNG-04788.py
Reverts tomiwaajayi/HNGi7-task-2#458
=> Revert "Revert "Hng 00987 2""

scripts/gfellah-HNG-02163.js
removed full stop from logged msg
=> gfellah-HNG-02163 edited

scripts/musaismail-HNG-03367.js
ismail is requesting a Pull Request.
=> musaismail-HNG-03367 script

scripts/ojchris-HNG-01003.php
Hi tomiwaajayi, hope this works. Though I wasn't sure if the username referred was slack or github.  Thanks
=> ojchris-HNG-01003 script

scripts/Oneharry-HNG-02652.js
Hey, i have modified my script.
=> modified Oneharry-HNG-02652 script

scripts/wamuyuwanjohi-HNG-05307.py
Added the json dump method to give json output
=> wamuyuwanjohi HNG-05307 script

scripts/urielone-HNG-04057.js
=> modified my js file urielone-HNG-04057.js

scripts/Danny97-HNG-01220.js
=> Danny97-HNG-01220 script

scripts/Tobiloba98-HNG-01882.js
Tobiloba is requesting for a new pull request after making some changes
=> Tobiloba98-HNG-01882 script

scripts/da_saint-HNG-00657.py
=> da_saint-HNG-00657.py

Golden-HNG-04717.js
Thanks a bunch at Orim.dominic, you're the real MVP.
=> Golden-HNG-04717.js

scripts/mistadane-HNG-00315.js
=> mistadane-HNG-00315 script

scripts/temmytope-HNG-03678.php
=> correction

scripts/CrafterDeo-HNG-01837.py
=> CrafterDeo-HNG-01837 script

scripts/Rex[02]-HNG-00720.js
=>  made changes to my script

scripts/swift_code-HNG-00500.js
swift_code created a pull request
=> swift_code-HNG-00500 script

scripts/Tura-HNG-02324.js
Errors Corrected, Kindly review and Merge.
=> Errors Corrected

scripts/Eguono- HNG 00921. js
fullName = 'Adarighofua Eguono Patience';
const hngId = 'HNG-00921';
const email = 'adarighofuaeguono@gmail.com';
const language = 'JavaScript';
console.log(`Hello World, this is ${fullName} with HNGi7 ID ${hngId} and email ${email} using ${language} for stage 2 task`);
=> Eguono-HNG-00921.js

scripts/sodiq-HNG-00472.js
I am done with my task! Now adding my script
=> Adding sodiq bamidele script for stage 2

scripts/Rome-HNG-00193.js
=> Rome-HNG-00193 script

scripts/Rome-HNG-00193.js
=> Rome-HNG-00193

scripts/leo.myke-HNG-01799.js
=> leo.myke-HNG-01799 script

scripts/Rex[02]-HNG-00720.js
i noticed i spelled "and" as "amd"
=> final change

scripts/smartbrain-HNG-05813.py
=> smartbrain-HNG-05813

scripts/chinwe-HNG-01015.js
=> chinwe-HNG-01015 script

scripts/tolulope-HNG-00377.js
- Update script with variable names
- Add console.log
=> Updated script

scripts/phrukey-HNG-04367.js
Please merge my script please. I'm sorry for being late please.
=> phrukey-HNG-04367 script final correction please

scripts/Phlora-HNG-06313.js
=> phlora HNG-06313 updated script

scripts/Hammed-HNG-00649.js
=> Hammed-HNG-00649 script

scripts/Demilade-HNG-01494.py
=> Demilade-HNG-01494 script

scripts/Abimbola-HNG-03780.js
=> ayindeabimbola-HNG-03780 script

scripts/VivieCodes-HNG-01929.PY
Hope this gets treated...thank you!!!
=> VivieCodes-HNG-01929

scripts/lolamedina-HNG-00746.js
=>  lolamedina HNG-00746

scripts/deedan19-HNG-01245.js
=> Corrections made

scripts/okaforelvis-HNG-03728.js
=> added space

scripts/mofiyin-HNG-01273.js
made a correction to my output
=> mofiyin-HNG-01273

scripts/ChuksFE-HNG-04687.js
=> ChuksFE-HNG-04687 script

scripts/tosin-HNG-00281.py
=> tosin-HNG-00281

scripts/deedan19-HNG-01245.js
=>  Newly Modified

scripts/tolulope-HNG-00377.js
=> HNG-00377-updated-script1

scripts/Oneharry-HNG-02652.js
=> update HNG-02652 script

Emma-HNG-01763.js
=> Emma-HNG-01763 updated

scripts/Theresa001-HNG-04217.js
=> Theresa001-HNG-04217 script

scripts/stonecode-HNG-00352.js
=> creating a commit to remove dot (.)

scripts/swift_code-HNG-00500.js
=> Hngi7 00500

scripts/silhouette-HNG-05751.js
Hi Guys!
My apologies for this chaotic error.
I used a different mail to the one I registered my slack with and as such though my status returned a 'Pass', I wasn't promoted due to this. 
I have corrected the error now.
Please kindly help 'Merge' my PR.
Thanks.
=> silhouette-HNG-05751

scripts/Bell-HNG-05536.js
=> Bell-HNG-05536 script

scripts/gfellah-HNG-02163.js
please review and merge made the adjustment
=> ajusted my output

scripts/KwennB-HNG-01909.js
=> corrections

scripts/jesusemenehimiyein-HNGi7-task-2.js
=> ull be fine

scripts/faidah-HNG-04259.py
=>  faidah-HNG-04259

scripts/arinze-HNG-02728.py
Reverts tomiwaajayi/HNGi7-task-2#833
=> Revert "update"

scripts/Jochoniah-HNGi7-HNG-01516.js
Hi, I have made another update. Thank you
slack name: @Jochoniah
=> Hng 01516: another update

scripts/chinonsoHE-HNG-05667.py
Hi Tomiwa,
Kindly merge my changes to the main repo.
Thanks
=> Script for Task 1
